name: Run Shell Commands
on: 
  push:
    branches: [ "main" ]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: WebdriverIO Automation
        run: echo "Github Actions Workflow"
